### ISSUE TITLE
inttypes.h not available for xc16 compiler

### ISSUE THREAD

**Issue by VIRGINIANEGRI25** [Jacajack/liblightmodbus#20]
I want to use liblightmodbus on a Microchip MCU (PIC24); unfortunately the xc16 compiler does not include the header inttypes.h. 
I replaced the file with stdint.h and the compilation was succesful and the resulting firmware worked correctly.
Is it possible that only stdint.h is required for liblightmodbus? if so, i would suggest to replace inttypes.h with stdint.h.
I can make a pull request if you wish!

**Comment by Jacajack** [comment]
Hello,

This problem was already mentioned in #19, and I was initially planning to fix it in the version 3.0. `stdint.h` should be sufficient, but I simply didn't realize that not all compilers had `inttypes.h`. Now I'm thinking that maybe this should be patched here too. If you're willing to make a pull request, sure, please go ahead :)

Thanks!
