### ISSUE TITLE
Can you help in porting for pic 18f6722 controller 

### ISSUE THREAD

**Issue by udaymedha** [Jacajack/liblightmodbus#30]
Please can you help in porting for pic micro controller pic 18f6722 with uart.

**Comment by Jacajack** [comment]
What do you mean by porting? The library is hardware agnostic, so you should be able to integrate it into your project without any major issues. Please see the [examples](https://github.com/Jacajack/liblightmodbus/tree/master/examples). However, if you you're asking for help with writing PIC-specific UART communications code, then I can't help you, simply because I am not at all familiar with PIC µCs. I suppose that conceptually UART usage won't be very different from AVR, so the AVR slave example might be especially useful for you.
