### ISSUE TITLE
modbusMasterInit() and LPC1768

### ISSUE THREAD

**Issue by PoojaEmbedded** [Jacajack/liblightmodbus#34]
I am new to Modbus communication, and I am trying to learn it. I am using LPC1768 as the master and the Raspberry Pi as the slave for Modbus communication. Everything is working fine when I use the second version of the liblightmodbus library. When using the third version, even though no error is there, when I call the modbusMasterInit() function in my main loop, it's blocking the microcontroller from doing anything. Thus, I am not getting any output. Can you tell where I am going wrong?

I am adding a snippet of my code for reference.

```c

int main(void)
{   
	SystemInit();
	debugInitialize(DEBUG_BAUDRATE);
	UART_Init(C_UartOne_U8, MODBUS_BAUDRATE);
	debugPrintf("Pendant powered up");	
	debugPrintf("Default function count = %d\n", modbusMasterDefaultFunctionCount);  
	
	ModbusErrorInfo err;
	err	= modbusMasterInit(
        &master,          
        dataCallback,                  		// Callback for handling incoming data
        masterExceptionCallback,					// Exception callback (optional)
        modbusDefaultAllocator,         	// Memory allocator used to allocate request
        modbusMasterDefaultFunctions,   	// Set of supported functions
        modbusMasterDefaultFunctionCount	// Number of supported functions
      );
	assert(modbusIsOk(err)); 
	
	debugPrintf("Modbus master initialized!"); 	
	
	osKernelInitialize();
	
	debugPrintf("Kernel initialized!");  	
	
	tid_thrMODBUS_COMM_Q = osThreadNew(MODBUS_COMM_Q, NULL, &MODBUS_COMM_Q_attr);
	
	osKernelStart();

	return 0;
}
```

**Comment by Jacajack** [comment]
Hi and sorry for my late response. I have to say I'm not quite sure what could be the issue here. There's no reason for `modbusMasterInit()` to fail really. It only calls `modbusBufferInit()` and it never fails:

https://github.com/Jacajack/liblightmodbus/blob/dd3b242af1bd63e56a15dd8c97e03490ac259638/include/lightmodbus/base.impl.h#L51-L62

Perhaps your code is hanging at this assertion for some strange reason: `assert(modbusIsOk(err));`? Could you please see what happens when you remove it? Did you try printing anything right after the `modbusMasterInit()` call?

**Comment by PoojaEmbedded** [comment]
Hi and thanks a lot for replying to my query.

As suggested, I tried the code after removing assert(modbusIsOk(err)), but
I'm still facing the same problem.
And yes, I tried printing after modbusMasterInit(), but I am getting
nothing at all.

I am sharing some screenshots for your reference. It would be a great help
if you could guide me through this.
For context, I am writing the code for the master of CNC controller. When I
press the reset button on it, I get the desired result (without_fn.png)
which happens when the function is not included.
And when the function is included, I get nothing after the reset button is
pressed (with_fn.png).

Thanks for your help
Pooja

**Comment by Jacajack** [comment]
That's interesting. Unfortunately, I can't see the attachments - it seems that they don't pass through GitHub's email system.

I assume that `master` is a global variable in your code. Could you please see what happens if you make it a local variable in the `main` function?

If the program keeps crashing, we'll need to dive deeper and see what internal code actually causes the error. You can start by replacing the return value in this function by `MODBUS_NO_ERROR()` and getting rid of the `modbusBufferInit()` call.

https://github.com/Jacajack/liblightmodbus/blob/dd3b242af1bd63e56a15dd8c97e03490ac259638/include/lightmodbus/master.impl.h#L79-L94

As far as I'm concerned, assignments such as these should never fail unless they are referring to some protected memory region or something like that. Sadly, I'm not familiar with your platform, so I don't know any of its quirks or limitations.

**Comment by PoojaEmbedded** [comment]
That's really silly of me that I didn't attach the photos properly. 
Here I am posting them.
Sorry for the inconvenience. 
1) With the function included:
![with_fn](https://github.com/Jacajack/liblightmodbus/assets/155071922/c079b003-b868-49c9-be3c-564a1544fc3b)
2) When the function is commented out.
![without_fn](https://github.com/Jacajack/liblightmodbus/assets/155071922/5983a964-a6a0-416f-b8cb-a4870380bb62)

And yes, you're right, `master` is global variable in my code.
I'll try out all the suggested solutions and  let you know if I got the desired result or not.

Thanks a bunch.

**Comment by Jacajack** [comment]
Glad to hear that worked for you! I wonder what was wrong with `master` being global. I assume that must be something platform-specific.
