### ISSUE TITLE
Unreachable statement in sregs.c

### ISSUE THREAD

**Issue by Milack27** [Jacajack/liblightmodbus#4]
When I compile the slave part of liblightmodbus, there's a warning about an unreachable statement in the function `modbusParseRequest16` from the file `sregs.c`, as shown in the following snippet:

    //Check if frame length is valid
    if ( status->request.length >= 7u )
    {
        frameLength = 9 + parser->request16.length;
        if ( status->request.length != frameLength )
        {
            return modbusBuildException( status, 16, MODBUS_EXCEP_ILLEGAL_VAL );
            return MODBUS_ERROR_OK;  // Unreachable!
        }
    }

**Comment by Jacajack** [comment]
Thanks for pointing that out!
Apart from generating warning (which surprisingly isn't generated by my compiler) that's a pretty serious issue, that hasn't been caught before due to [lack of tests for that code fragment](https://coveralls.io/builds/11790369/source?filename=src%2Fslave%2Fsregs.c#L190).

I'm think that this is what I've meant:
```c
//Check if frame length is valid
if ( status->request.length >= 7u )
{
	frameLength = 9 + parser->request16.length;
	if ( status->request.length != frameLength )
	{
		if ( parser->base.address != 0 ) return modbusBuildException( status, 16, MODBUS_EXCEP_ILLEGAL_VAL );
		return MODBUS_ERROR_OK;
	}
}
```
